#! /bin/sh

function usage() {
  echo "Usage: $0 <run-dir> [#-cores]"
  exit 10
}

( [[ $# -lt 1 ]] || [[ $# -gt 2 ]] ) && usage

# base working directory
BASE=$1
# number of cores
CORES=${2:-"1 2 3"} # 4 5 6 7 8 16 32 64"} #default

# arg checks
for N in $CORES; do
  [[ "$N" -lt 1 ]] && echo "error: #-cores must be >= 1" && usage
done
[[ ! -d $BASE ]] && echo "error: base-dir '$BASE' does not exist" && usage

MC=meagre-crowd
MC_ARGS="-tv" # one iteration

SUB=sqsub
SUB_ARGS="-n $N -r 15m --mpp=1G -q mpi"
SUB_ARGS_1="-n 1 -r 15m --mpp=1G -q serial" # special options for single core

INPUT_DIR=matrices
MATRICES="Bai/dwa512 Bai/dw4096 Bai/dw8192" # ATandT/onetone2 Freescale/transient Freescale/memchip Freescale/Freescale1 Freescale/circuit5M"


$SUB -h &> /dev/null
[[ $? -eq 127 ]] && echo "Missing $SUB!" && exit 1

echo "Checking all matrices are present:"
cd ${BASE}
mkdir -p ${INPUT_DIR}
cd ${INPUT_DIR}
for i in ${MATRICES}; do
  M=$(basename $i)
  D=$(dirname $i)
  echo "  ${INPUT_DIR}/$i.mm"
  if [[ ! -f $i.mm ]]; then
    wget http://www.cise.ufl.edu/research/sparse/MM/$i.tar.gz > /dev/null
    tar zxvf $M.tar.gz > /dev/null
    [[ ! -d "$D" ]] && mkdir $D
    mv $M/$M.mtx $D/$M.mm # Note: we like .mm, Univ. Florida Sparse Matrix collection says .mtx
    rm -rf $M.tar.gz $M
  fi
done
cd - > /dev/null


echo "Launching jobs:"
OUTPUT_DIR=$(mktemp -d ${BASE}/results-$(date +%Y%m%d).XXXX)

function launch_job() {
  i=$1
  N=$2
  S=$3
  SA=${SUB_ARGS}
  [[ $N -eq 1 ]] && SA=${SUB_ARGS_1}
  ${SUB} ${SA} \
    -o ${OUTPUT_DIR}/$i-$N-$S.log \
    -e ${OUTPUT_DIR}/$i-$N-$S.err \
    -j "MC($S:$N:$i)" \
    ${MC} -i ${BASE}/${INPUT_DIR}/$i.mm ${MC_ARGS} -s $S \
      >> ${OUTPUT_DIR}/jobids
}
[[ -f ${OUTPUT_DIR}/jobids ]] && rm ${OUTPUT_DIR}/jobids # clear the jobid list if it exists
for i in ${MATRICES}; do
  M=$(basename $i)
  D=$(dirname $i)
  mkdir -p ${OUTPUT_DIR}/$D
  echo -n "  ${INPUT_DIR}/$i.mm - mumps: "
  for N in ${CORES}; do
    launch_job $i $N mumps
    echo -n "$N, "
  done
  launch_job $i 1 umfpack
  echo "umfpack: 1"
done

echo "Saving list"
echo "${MATRICES}" > ${OUTPUT_DIR}/matrices
echo "  output: ${OUTPUT_DIR}"

# TODO launch a final job that waits for the other jobs, then summarizes the results
